### ISSUE TITLE
Escolha da Plataforma de Armazenamento.

### ISSUE THREAD

**Issue by Miguelito001** [thiagomeller/pipeline-conta-digital#13]
**Plataformas de Armazenamento Gratuitas**

> ### Amazon S3 (AWS Free Tier)
>
> Detalhes: Oferece 5 GB de armazenamento padrão (S3 Standard).
> Limitações: Inclui 20.000 GET e 2.000 PUT requests.
> Link: [AWS Free Tier](https://aws.amazon.com/free/)

> ### Azure Blob Storage (Azure Free Account)
>
> Detalhes: Oferece 5 GB de armazenamento de Blobs.
> Limitações: 20.000 operações de leitura e 10.000 operações de gravação.
> Link: [Azure Free Account](https://azure.microsoft.com/free/)

> ### Google Cloud Storage (Google Cloud Free Tier)
>
> Detalhes: Oferece 5 GB de armazenamento em regiões específicas.
> Limitações: Inclui 5.000 operações de classe A e 50.000 operações de classe B.

> ### IBM Cloud Object Storage (IBM Cloud Free Tier)
>
> Detalhes: Oferece 25 GB de armazenamento por mês.
> Limitações: Inclui um número limitado de operações.

**Comment by thiagomeller** [comment]
Cara, eu acho que a princípio vamos utilizar o Azure que é o que a gente vem vendo em aula e temos mais familiaridade.
Porém, se tu tem mais facilidade com outro a gente pode trocar.

**Comment by Miguelito001** [comment]
Então, eu abri a issue para que caso alguém tenha algum conhecimento melhor em alguma plataforma e queira que seja usado para o projeto, como eu também não conheço muito sobre o assunto então estou disposto a usar o que vocês escolherem.

**Comment by GuiDalmolin** [comment]
Não tenho um conhecimento melhor de outra plataforma, o azure está de bom tamanho para o projeto.

**Comment by thiagomeller** [comment]
Será utilizado o Azure ADLS
