### ISSUE TITLE
Escolha da plataforma de Processamento.

### ISSUE THREAD

**Issue by Miguelito001** [thiagomeller/pipeline-conta-digital#14]
**Plataformas de Processamento Gratuitas**

> ### Apache Spark (Databricks Community Edition)
> 
> Detalhes: Oferece uma versão gratuita do Databricks, permitindo o uso de Apache Spark.
> Limitações: Recursos limitados e suporte básico.

> ### Google BigQuery (Google Cloud Free Tier)
> 
> Detalhes: Oferece 1 TB de consultas gratuitas por mês.
> Limitações: Até 10 GB de armazenamento gratuito.

> ### Azure Data Factory (Azure Free Account)
> 
> Detalhes: Oferece 5.000 atividades de movimentação de dados por mês.
> Limitações: Inclui 1.000 atividades de pipeline de dados.
> Link: [Azure Free Account](https://azure.microsoft.com/free/)

> ### AWS Glue (AWS Free Tier)
> 
> Detalhes: Oferece 1 milhão de acessos de dados gratuitos por mês.
> Limitações: Inclui 10 DPU-hours (Unidades de Processamento de Dados) por mês.
> Link: [AWS Free Tier](https://aws.amazon.com/free/)

> ### Google Dataflow (Google Cloud Free Tier)
> 
> Detalhes: Oferece 50 horas de job de streaming e 50 horas de job de batch por mês.
> Limitações: Recursos limitados após a cota gratuita.

**Comment by thiagomeller** [comment]
Seguindo a mesma lógica, acredito que Apache Spark pois já temos certa familiaridade. Tem outro que tu gostaria de usar?

**Comment by Miguelito001** [comment]
Concordo que o Apache Spark seja a melhor opção, porem deixamos aqui uma área para que todos possam entrar em acordo com as tecnologias escolhidas.

**Comment by GuiDalmolin** [comment]
Sigo com Apache Spark.

**Comment by thiagomeller** [comment]
Optamos por Apache Spark
