### ISSUE TITLE
Escolha da ferramenta de Automatização.

### ISSUE THREAD

**Issue by Miguelito001** [thiagomeller/pipeline-conta-digital#15]
**Ferramentas de Automação Gratuitas**

>###  Apache Airflow
> 
> Detalhes: Plataforma de código aberto para criar, agendar e monitorar workflows programaticamente.
> Características: Integração com várias fontes de dados, pipelines definidos em Python.
> Link: [Apache Airflow](https://airflow.apache.org/)

> ### GitHub Actions
> 
> Detalhes: Plataforma de CI/CD que permite automatizar fluxos de trabalho diretamente no GitHub.
> Características: 2.000 minutos gratuitos por mês para repositórios públicos e privados.
> Link: [GitHub Actions](https://github.com/features/actions)

> ### Jenkins
> 
> Detalhes: Ferramenta de automação de código aberto para integração contínua e entrega contínua.
> Características: Extensível com muitos plugins, forte comunidade de suporte.
> Link: [Jenkins](https://www.jenkins.io/)

> ### Google Cloud Functions
> 
> Detalhes: Plataforma de computação sem servidor que executa código em resposta a eventos.
> Características: 2 milhões de execuções gratuitas por mês.

> ### AWS Lambda (AWS Free Tier)
> 
> Detalhes: Plataforma de computação sem servidor que permite executar código sem provisionar ou gerenciar servidores.
> Características: 1 milhão de solicitações gratuitas por mês.
> Link: [AWS Lambda](https://aws.amazon.com/lambda/)

**Comment by thiagomeller** [comment]
Comecei a dar uma olhada no Apache Airflow, mas não conheço nenhum. Se alguém tiver familiaridade com outro podemos usar.

**Comment by Miguelito001** [comment]
Encontrei um repositório com muitas informações interessantes e que pode ajudar no desenvolvimento deste projeto.

**https://github.com/DataExpert-io/data-engineer-handbook?tab=readme-ov-file**

**Comment by thiagomeller** [comment]
Opa, ótimo!

**Comment by thiagomeller** [comment]
Acabamos usando Databricks para fazer toda a automação

**Comment by thiagomeller** [comment]
Optamos pelo Workflow do Databricks
