### ISSUE TITLE
Escolha da ferramenta de Monitoramento.

### ISSUE THREAD

**Issue by Miguelito001** [thiagomeller/pipeline-conta-digital#16]
**Ferramentas de Monitoramento Gratuitas**

> ### Prometheus
> 
> Detalhes: Sistema de monitoramento e alerta de código aberto, projetado para a coleta de métricas de tempo de execução.
> Características: Forte integração com Kubernetes, suporte a diversas fontes de dados.
> Link: [Prometheus](https://prometheus.io/)

> ### Grafana
> 
> Detalhes: Plataforma de análise e visualização de métricas de código aberto.
> Características: Integração com várias fontes de dados, dashboards interativos.
> Link: [Grafana](https://grafana.com/)

> ### Zabbix
> 
> Detalhes: Plataforma de monitoramento de código aberto para redes, servidores, aplicações e serviços.
> Características: Coleta de dados em tempo real, alertas configuráveis, dashboards personalizáveis.
> Link: [Zabbix](https://www.zabbix.com/)

> ### Nagios Core
> 
> Detalhes: Ferramenta de monitoramento de sistemas e redes de código aberto.
> Características: Monitoramento de hosts, serviços e métricas, suporte a plugins.

> ### Azure Monitor (Azure Free Account)
> 
> Detalhes: Serviço de monitoramento que fornece insights completos sobre suas aplicações e infraestrutura.
> Características: 5 GB de dados de log, 10 alertas de alertas e 1.000 consultas de log gratuitos por mês.
> Link: [Azure Monitor](https://azure.microsoft.com/en-us/services/monitor/)

**Comment by thiagomeller** [comment]
Essa eu não sei dizer, o que recomendas?

**Comment by thiagomeller** [comment]
Acabamos não necessitando.
