### ISSUE TITLE
Desenvolver o desenho da arquitetura

### ISSUE THREAD

**Issue by Miguelito001** [thiagomeller/pipeline-conta-digital#22]
### Desenvolver o desenho da arquitetura

deve ser colocado no **README** por pedido do professor, mas pra isso devemos decidir quais tecnologias realmente serão utilizadas e quando.

**Comment by thiagomeller** [comment]
Processamento -> Apache Spark
Armazenamento -> Azure ADLS
Automação -> Databricks Workflow

**Comment by Miguelito001** [comment]
Desenvolvido desenho da Arquitetura 

![Ingest](https://github.com/thiagomeller/pipeline-conta-digital/assets/100603408/0d77139e-fe1f-4794-b91a-4f35fe7b72c4)
