### ISSUE TITLE
Quais serão nossas métricas?

### ISSUE THREAD

**Issue by thiagomeller** [thiagomeller/pipeline-conta-digital#8]
Comentem sugestões e possíveis métricas
4 KPI - números (porcentagens, valores crus, etc...)
2 gráficas

**Comment by thiagomeller** [comment]
Pensei em, quantidade de cartões de crédito vs débito

**Comment by Miguelito001** [comment]
### KPI

**Média** dos valores das aplicações _(Poupança, CDB, RDB, Fundos de Investimento)_
**Média** dos saldos das contas bancárias dos usuários.

### GRAFICOS

**Percentual** de cada tipo de transação.
**Percentual** de cartões de crédito e débito emitidos.

**Comment by thiagomeller** [comment]
KPI
Média dos valores das aplicações (Poupança, CDB, RDB, Fundos de Investimento)
Média dos saldos das contas bancárias dos usuários.
Numero de usuários ativos (fizeram 1 transação a pelo menos 2 meses)
Percentual de cada tipo de transação.

GRAFICOS
Variação dos juros em empréstimos no ultimo ano
Relação de cartões de crédito e débito emitidos.

**Comment by thiagomeller** [comment]
KPIs:
Usuários ativos - Feita movimentação nos últimos 2 meses
Valor médio das contas bancárias
Valor médio das aplicações
Cartões ativados - quantidade últimos 6 meses

Métricas:
Limite de crédito em relação ao saldo da conta]
Média de valores por aplicação 

![image](https://github.com/thiagomeller/pipeline-conta-digital/assets/42391994/973b9533-3054-49a2-8532-534dc687a3b0)
